-- SPDX-FileCopyrightText: 2026 Kristofer Älvring <kristofer@mainly.ai>
-- SPDX-FileCopyrightText: 2026 Leah Lundqvist <leah@mainly.ai>
--
-- SPDX-License-Identifier: GPL-2.0-only

INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-101-1", "GRI-101", NOW(), NOW(), NOW(), "Reporting Principles");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-101-2", "GRI-101", NOW(), NOW(), NOW(), "Using the GRI Standards for sustainability reporting");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-101-3", "GRI-101", NOW(), NOW(), NOW(), "Making claims related to the use of the GRI Standards");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-1", "GRI-102", NOW(), NOW(), NOW(), "Organizational profile");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-2", "GRI-102", NOW(), NOW(), NOW(), "Strategy");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-3", "GRI-102", NOW(), NOW(), NOW(), "Ethincs and Integrity");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-3", "GRI-102", NOW(), NOW(), NOW(), "Ethincs and Integrity");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-4", "GRI-102", NOW(), NOW(), NOW(), "Governance");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-5", "GRI-102", NOW(), NOW(), NOW(), "Stakeholder Engagement");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-102-6", "GRI-102", NOW(), NOW(), NOW(), "Reporting Practice");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-103-1", "GRI-103", NOW(), NOW(), NOW(), "General Requirements for reporting the management approach");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-201-1", "GRI-201", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-201-2", "GRI-201", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-202-1", "GRI-202", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-202-2", "GRI-202", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-203-1", "GRI-203", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-203-2", "GRI-203", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-204-1", "GRI-204", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-204-2", "GRI-204", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-205-1", "GRI-205", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-205-2", "GRI-205", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-206-1", "GRI-206", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-206-2", "GRI-206", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-207-1", "GRI-207", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-207-2", "GRI-207", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-301-1", "GRI-301", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-301-2", "GRI-301", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-302-1", "GRI-302", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-302-2", "GRI-302", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-303-1", "GRI-303", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-303-2", "GRI-303", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-303b-1", "GRI-303b", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-303b-2", "GRI-303b", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-304-1", "GRI-304", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-304-2", "GRI-304", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-305-1", "GRI-305", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-305-2", "GRI-305", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-306-1", "GRI-306", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-306-2", "GRI-306", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-307-1", "GRI-307", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-307-2", "GRI-307", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-308-1", "GRI-308", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-308-2", "GRI-308", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-401-1", "GRI-401", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-401-2", "GRI-401", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-402-1", "GRI-402", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-402-2", "GRI-402", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-403-1", "GRI-403", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-403-2", "GRI-403", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-403b-1", "GRI-403b", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-403b-2", "GRI-403b", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-404-1", "GRI-404", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-404-2", "GRI-404", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-405-1", "GRI-405", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-405-2", "GRI-405", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-406-1", "GRI-406", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-406-2", "GRI-406", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-407-1", "GRI-407", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-407-2", "GRI-407", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-408-1", "GRI-408", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-408-2", "GRI-408", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-409-1", "GRI-409", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-409-2", "GRI-409", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-410-1", "GRI-410", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-410-2", "GRI-410", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-411-1", "GRI-411", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-411-2", "GRI-411", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-412-1", "GRI-412", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-412-2", "GRI-412", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-413-1", "GRI-413", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-413-2", "GRI-413", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-414-1", "GRI-414", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-414-2", "GRI-414", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-415-1", "GRI-415", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-415-2", "GRI-415", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-416-1", "GRI-416", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-416-2", "GRI-416", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-417-1", "GRI-417", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-417-2", "GRI-417", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-418-1", "GRI-418", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-418-2", "GRI-418", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-419-1", "GRI-419", NOW(), NOW(), NOW(), "Management Approach Disclosures");
INSERT INTO gri_category (Category_ID, Topic_Codename, Last_used, Last_updated, Time_created, Name) VALUES ("GRI-419-2", "GRI-419", NOW(), NOW(), NOW(), "Topic-Specific Disclosures");