name: pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
      - run: uv sync --all-extras --locked
      - run: uv run poe ci:fmt
      - run: uv run poe ci:lint